version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app/android"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "com.google.ai.edge.litertlm:litertlm-android"
